language: java

notifications:
  email: false

jdk:
- oraclejdk8

after_success:
  - mvn --help
  - mvn dependency:tree -B
  - bash <(curl -s https://copilot-valid.blackducksoftware.com/ci/travis/scripts/upload)
