language: java

notifications:
  email: false

jdk:
- oraclejdk8

after_success:
  - export DETECT_LATEST_RELEASE_VERSION=2.4.0
  - bash <(curl -s https://blackducksoftware.github.io/hub-detect/hub-detect.sh) --detect.output.path=.copilot --detect.bom.aggregate.name=copilot_bom_bdio --detect.hub.signature.scanner.disabled=true --detect.maven.build.command=\"-B\" --blackduck.hub.offline.mode=true
